# #######################################################################################
# HYPRPAPER CONFIGURATION (0.0% CPU Native C++ Daemon)
# #######################################################################################

splash = false
ipc = on
