# Hyprpaper - Native, lightweight C++ wallpaper daemon for Hyprland
preload = /home/cyberdev/Pictures/Wallpapers/Retro_Terminal_Workstation.png
wallpaper = ,/home/cyberdev/Pictures/Wallpapers/Retro_Terminal_Workstation.png
splash = false
ipc = on
